# read secret tokens from environment variables
verifyToken: ${RMNDR_VERIFY_TOKEN}
pageAccessToken: ${RMNDR_ACCESS_TOKEN}
appSecret: ${RMNDR_APP_SECRET}

server:
    type: default
    applicationConnectors:
        -   type: http
            port: ${PORT:-5000}

logging:
  level: INFO
  loggers:
    manfredlift.facebook.rmndr: INFO
  appenders:
    - type: console
    - type: file
      threshold: INFO
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: /tmp/rmndr.log
      archivedLogFilenamePattern: /tmp/rmndr-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: UTC
      maxFileSize: 10MB

jerseyClient:
  minThreads: 1
  maxThreads: 128
  workQueueSize: 8
  gzipEnabled: true
  gzipEnabledForRequests: true
  chunkedEncodingEnabled: true
  timeout: 3s